### ISSUE TITLE
What does this line work for? Thanks.

### ISSUE THREAD

**Issue by JinYue2015** [FoundationVision/Infinity#10]
https://github.com/FoundationVision/Infinity/blob/0ac8556fa2cc23c70c342785e53145c5d6b09d46/infinity/models/infinity.py#L433

**Comment by JeyesHan** [comment]
This line is to quick jump to the implementation of [SelfAttnBlock.forward, CrossAttnBlock.forward]. It's for reference only and no other special usuage.
