### ISSUE TITLE
what is the correct path for model_path?

### ISSUE THREAD

**Issue by Alisaleelee** [FoundationVision/Infinity#12]
Thx for your nice work, I met errors in assert ('ar-' in model_path) or ('slim-' in model_path).
I did not find a path including 'ar' or 'slim'
![image](https://github.com/user-attachments/assets/c3d7ab0c-19cf-4317-98e4-4427e1a5f3b0)

**Comment by JeyesHan** [comment]
@Alisaleelee Thanks for your attention. I have update the code. You can pull latest commit and try again.
