### ISSUE TITLE
Dependency "flash_attn" is missing?

### ISSUE THREAD

**Issue by costrice** [FoundationVision/Infinity#14]
It seems like the project uses the python library "flash_attn" in the following codes:
https://github.com/FoundationVision/Infinity/blob/ea04127aa5812a82d0a0c55603fba0499268442c/infinity/models/basic.py#L18
But this dependency does not appear in the requirements.txt or README? 
And when I tried to run the jupyter notebook, an error raised:

> ModuleNotFoundError: No module named 'flash_attn'

**Comment by EternalEvan** [comment]
I solve it by:
`pip install flash_attn==2.6.3`
you can try if it works.
