### ISSUE TITLE
Performance drop without prompt rewriting.

### ISSUE THREAD

**Issue by csguoh** [FoundationVision/Infinity#16]
Hi, authors.

Thanks for sharing this incredible work. I have tried the Infinity-2B model and tested it on the GenEval benchmark.  However, since I have no access to the OpenAI api to rewrite the prompt, I thus set the `--rewrite_prompt = 0`, and keep other parameters the same as the default. The following is my reproduce results.

```
Summary
=======
Total images: 2212
Total prompts: 553
% correct images: 67.18%
% correct prompts: 80.47%

Task breakdown
==============
counting         = 62.19% (199 / 320)
two_object       = 77.02% (305 / 396)
colors           = 84.57% (318 / 376)
color_attr       = 59.75% (239 / 400)
position         = 26.75% (107 / 400)
single_object    = 99.38% (318 / 320)

Overall score (avg. over tasks): 0.68276
````

Compared with the reported results with prompt rewriting in the paper, it seems there is a performance drop with my implementation. Since I have not found the results of Infinite model w/o prompt rewriting, I wonder whether my reproduce results is roughly correct?

Thanks for your help!

**Comment by JeyesHan** [comment]
@csguoh Thans for your appreciation to Infinity.
The overall GenEval score withour rewriting is around 0.69. Below is my tested result before.

Summary
=======
Total images: 2212
Total prompts: 553
% correct images: 67.63%
% correct prompts: 80.83%

Task breakdown
==============
single_object    = 99.69% (319 / 320)
two_object       = 78.28% (310 / 396)
counting         = 64.69% (207 / 320)
colors           = 84.31% (317 / 376)
position         = 25.25% (101 / 400)
color_attr       = 60.50% (242 / 400)

Overall score (avg. over tasks): 0.68786

I think your results is roughly correct. Hope you enjoy playing with Infinity.

**Comment by JeyesHan** [comment]
[prompt_rewrite_cache.json](https://github.com/user-attachments/files/18260941/prompt_rewrite_cache.json)
@csguoh 
You can try this file to test GenEval with prompt rewriting. We cached the rewrited prompts such that you can test rewriting results without OpenAI api.

**Comment by csguoh** [comment]
Perfect! Thanks for your reply and this prompt-rewriting file.
