### ISSUE TITLE
Hoping for the Release of a Small Sub-Dataset！

### ISSUE THREAD

**Issue by Foxerity** [FoundationVision/Infinity#17]
The _Infinity_ is absolutely amazing! The results are stunning, and I had a lot of fun playing with the demos on Discord—such a cool experience.

I saw you mentioned using a smaller sub-dataset to train a smaller models, and I was wondering if there's any chance you might share that sub-dataset or something smaller? I’m really excited to follow  _Infinity_ and try out some fun ideas, but I’m struggling to find a suitable dataset to get started.

Thanks so much for your incredible work!

**Comment by JeyesHan** [comment]
@Foxerity Thanks for your appreciation to Infinity. Sadly, we are not allowed to release data according to the regulations. May be you could start with the LAION and COYO data with high aesthetic scores / ImageReward / HPS v2.1.
