### ISSUE TITLE
time estimation for the checkpoint release?

### ISSUE THREAD

**Issue by JosephZZ** [FoundationVision/Infinity#2]
any relatively precise time estimate? in how many weeks?
also will you release all sizes of the model mentioned in the paper? we actually look forward to use a small model for our project

thank you!

**Comment by JeyesHan** [comment]
Thanks for your attention to Infinity. We expect to release models (including the tokenizer & transformer) & code in the coming several weeks.

**Comment by GradOpt** [comment]
> Thanks for your attention to Infinity. We expect to release models (including the tokenizer & transformer) & code in the coming several weeks.

Anticipating the release! We’re also curious if smaller versions of Infinity (under 2B) will be released, as mentioned in the paper

**Comment by iFighting** [comment]
@GradOpt @JosephZZ 
We have already released the training code and models
