### ISSUE TITLE
Inquiry about Infinity model release

### ISSUE THREAD

**Issue by NielsRogge** [FoundationVision/Infinity#3]
Hello @iFighting 🤗

I'm Niels from the Hugging Face open-source team. I came across your work on Infinity through Hugging Face Papers (https://huggingface.co/papers/2412.04431).  Your paper is quite impressive!

Your README mentions a plan to release the Infinity-2B model, including checkpoints and inference code.  We at Hugging Face are very interested in hosting this model on our hub (https://huggingface.co/models) once it's ready.  Hosting on Hugging Face offers increased visibility and discoverability for your research, allowing for easier access by the community and enabling integration with other tools and workflows.

We can assist with the upload process and add relevant metadata tags to the model card to maximize its discoverability and impact. Could you provide an update on the expected release timeline? We're excited to see the model released and would be happy to help in any way we can.

Kind regards,
Niels

**Comment by JeyesHan** [comment]
It will be great if you guys could host Infinity on Hugging Face! We expect to release models (including the tokenizer & transformer) & code in the coming several weeks.

**Comment by iFighting** [comment]
@NielsRogge We have released the training code and models~

**Comment by NielsRogge** [comment]
Thank you!
