### ISSUE TITLE
[ Question ]: Infinity model in context of game playing like Genie 2 ? 

### ISSUE THREAD

**Issue by Viddesh1** [FoundationVision/Infinity#4]
Hello Team,

Great work, I have a question:-

I just read an article of Genie 2 below :-
 https://deepmind.google/discover/blog/genie-2-a-large-scale-foundation-world-model/

What do you think by using infinity model there is a scope for HD quality image generation in Genie 2 context?

Regards!
Viddesh

**Comment by iFighting** [comment]
@Viddesh1 Thank you for your interest in our paper. I think it's definitely ok for using infinity to generate HD quality images.
Also, in the future, infinite can also generate high quality videos.
