### ISSUE TITLE
有点没看懂,请问我的概况对吗?

### ISSUE THREAD

**Issue by YilanWang** [FoundationVision/Infinity#5]
就是说,在离散化的生成任务里,一般最后要对codebook取argmax,本质上就是个多标签里套了个多分类任务.但是一点轻微的区别就会导致index不对,这不好.
所以我们的层级就不要去做"那么argmax"的事情,只要分类为-1,+1,也就是正负样本级别就可以了?相当于就像faster-rcnn,咱们把rpn做好就可以了,就不用去做后边的rcnn.因为对于生成来说已经够用了.请问是这个意思吗?

**Comment by JeyesHan** [comment]
对codebook取argmax是指？

**Comment by YilanWang** [comment]
> 对codebook取argmax是指？

就是我看了下这种需要离散codebook的应该都是
得到latent->和embedding matmul->argmax得到最大值->scatter分配0,1->和codebook相乘得到最后的结果
这样的流程吧?那我感觉不精准的说,我们就是相当于对于多个codebook或者说多个dim(多标签),求每个标签的最大值(多分类).

**Comment by YilanWang** [comment]
另外想请教下,我记得之前生成类工作是不是也证明过这种观点?就是类似1024x256的codebook不如4096x64之类

**Comment by JeyesHan** [comment]
> > 对codebook取argmax是指？
> 
> 就是我看了下这种需要离散codebook的应该都是 得到latent->和embedding matmul->argmax得到最大值->scatter分配0,1->和codebook相乘得到最后的结果 这样的流程吧?那我感觉不精准的说,我们就是相当于对于多个codebook或者说多个dim(多标签),求每个标签的最大值(多分类).

VAR采用的VQ是你上述的这个流程。Infinity采用的是LFQ或者BSQ，是没有codebook的，将d维的特征符号量化后再转成index，当做一个分类任务去预测。Infinity不预测index，直接预测符号量化后的特征

**Comment by JeyesHan** [comment]
> 另外想请教下,我记得之前生成类工作是不是也证明过这种观点?就是类似1024x256的codebook不如4096x64之类

这个我不是很清楚，有相关文献的话可以发我一下

**Comment by YilanWang** [comment]
多谢大佬的解读,我理解了.
但是还有一个问题想知道一下,咱们这种var是[ar]是因为预测r_k的时候,用的是r_k-1,r_k-2....,r_1. 那有没有用实验证明过如果预测r_k的时候只用r_k-1呢(i.e., 变成马尔可夫过程)? 如果这样也行的话,那感觉方法成立的原因是cause to fine而不是自回归吧?

**Comment by iFighting** [comment]
> 多谢大佬的解读,我理解了. 但是还有一个问题想知道一下,咱们这种var是[ar]是因为预测r_k的时候,用的是r_k-1,r_k-2....,r_1. 那有没有用实验证明过如果预测r_k的时候只用r_k-1呢(i.e., 变成马尔可夫过程)? 如果这样也行的话,那感觉方法成立的原因是cause to fine而不是自回归吧?

@YilanWang 
不好意思，我们没有实验过这个setting，另外由于我们使用了multi scale residual quantization, 即使用到了上一个r_k的token，这里面也是包括之前所有的scale的信息的。

Sorry, we have not experimented with this setting. Additionally, since we use multi-scale residual quantization, which involves using the tokens from the previous \( r_k \), it inherently includes information from all previous scales.

Since Github is mainly english community, we sincerely prefer you to use english to discuss with each other

**Comment by iFighting** [comment]
> 多谢大佬的解读,我理解了. 但是还有一个问题想知道一下,咱们这种var是[ar]是因为预测r_k的时候,用的是r_k-1,r_k-2....,r_1. 那有没有用实验证明过如果预测r_k的时候只用r_k-1呢(i.e., 变成马尔可夫过程)? 如果这样也行的话,那感觉方法成立的原因是cause to fine而不是自回归吧?

In addition, I disagree with your hypothesis on this issue. Intuitively, using all the tokens of the previous scale would be better than using the tokens of the previous scale, and you can do some experiments to prove it.

**Comment by YilanWang** [comment]
多谢大佬，你完全回答了我的困惑，I close this issue

**Comment by YilanWang** [comment]
是的，我也在想这件事，residual的方式必须会包括之前所有信息。。这甚至很难做到不包括
