### ISSUE TITLE
Quesiton about training and (possibly) finetuning the model

### ISSUE THREAD

**Issue by costrice** [FoundationVision/Infinity#6]
Hi, thanks for your impressive work on image generation!

I anticipate using it as a generative backbone of my future work, so I am a bit curious about how many GPU resources are needed to train the model from scratch. More importantly, is it possible to finetune the model (like we commonly did on diffusion-based models like SD) using fewer GPU resources? Could you please provide some information? Thanks very much!

**Comment by JeyesHan** [comment]
Training from scratch is very expensive especially for the 1024x1024 resolution. We highly recommand you finetune **Infinity**. According to our full-params fine-tuning test, a iteration takes around 6s for one GPU, where bs=4, resolution=1024x1024.

**Comment by wxxhaoshuai** [comment]
hi, I would like to know how many computing resources are required to train the 125M model from scratch and how many are required to finetune？

**Comment by JeyesHan** [comment]
@wxxhaoshuai 
Apart from the model size, computing resources also depend on the data size and the targe resolution. I think 16 gpu cards (A100 or H100) are enough for training 125M model from scratch under 256x256 resolution.

**Comment by wxxhaoshuai** [comment]
Will you release the smaller checkpoint？such as 125M or 1B.

**Comment by JeyesHan** [comment]
@wxxhaoshuai These small models are trained with a small subset of the whole dataset and used for demonstrating the scaling capability of Infinity. **They are not full trained with abundant data, resolutions , iterations.** Therefore, we have no plan to release samller models for Infinity😭. We plan to release Infinity-20B.
