### ISSUE TITLE
The link of Infinity-2B checkpoint  is 404.

### ISSUE THREAD

**Issue by onepeachbiubiubiu** [FoundationVision/Infinity#9]

**Comment by JeyesHan** [comment]
Please wait a moment, the file is quite large, I am uploading it to Hugging Face.

**Comment by JeyesHan** [comment]
@onepeachbiubiubiu Uploading is done. Please pull latest commit and try it.

**Comment by onepeachbiubiubiu** [comment]
The link of toy dataset with 10 images is 404.

**Comment by JeyesHan** [comment]
I have uploaded it.
